let bitcoin_json = {
    "bpi":{
        "EUR":{
            "code":"EUR",
            "description":"Euro",
            "rate":"815.8994",
            "rate_float":815.8994,
            "symbol":"&euro;"
        },
        "GBP":{
            "code":"GBP",
            "description":"British Pound Sterling",
            "rate":"677.4879",
            "rate_float":677.4879,
            "symbol":"&pound;"
        },
        "USD":{
            "code":"USD",
            "description":"United States Dollar",
            "rate":"728.4816",
            "rate_float":728.4816,
            "symbol":"&#36;"
        }
    },
    "chartName":"Bitcoin",
    "disclaimer":"This data was generated by creating random numbers and mimics the Coinbase API JSON response structure. It is NOT real data. DO NOT USE THIS TO TRADE CRYPTOCURRENCY!",
    "time":{
        "updatedISO":"2023-02-14T20:16:14.370072"
    }
}

// Goal - convert $100 to Bitcoin,  so we need the rate_float for USD.

// console.log(bitcoin_json)

let bpi = bitcoin_json.bpi
// console.log(bpi)

for (let currency in bpi) {  // loop over every property in an object
    let data = bpi[currency]  // get the value for the current property
    console.log(`${currency} ${data.description}`)  // process the data
    // todo - include other info about other currencies
}

let usdInfo = bpi.USD
// console.log(usdInfo)

let usdExchangeRate = usdInfo.rate_float
console.log(usdExchangeRate)

// Equivalent of the lines above
let usdExchangeRateAnotherWay = bitcoin_json.bpi.USD.rate_float


let dollars = 100
let bitcoinEquivalent = dollars * usdExchangeRate
console.log(bitcoinEquivalent)
console.log(`$${dollars} is equivalent to ${bitcoinEquivalent} bitcoin`)